export const CLIENT_API_BASE = '/clients';
export const CLIENT_MANY_URL = CLIENT_API_BASE;
export const CLIENT_GET_URL = CLIENT_API_BASE;
export const CLIENT_CREATE_URL = CLIENT_API_BASE;
export const CLIENT_UPDATE_URL = CLIENT_API_BASE;